// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: Statements
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			reduce(3), // @, reduce: Statements
			reduce(3), // identifier, reduce: Statements
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(3), // if, reduce: Statements
			reduce(3), // while, reduce: Statements
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // empty
			nil,          // lbrace
			nil,          // rbrace
			nil,          // @
			nil,          // identifier
			nil,          // assign
			nil,          // terminator
			nil,          // [
			nil,          // intLit
			nil,          // ]
			nil,          // if
			nil,          // while
			nil,          // else
			nil,          // plus
			nil,          // minus
			nil,          // mul
			nil,          // ==
			nil,          // <
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Program
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			shift(4),  // @
			shift(5),  // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			shift(6),  // if
			shift(7),  // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: Statements
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			reduce(2), // @, reduce: Statements
			reduce(2), // identifier, reduce: Statements
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(2), // if, reduce: Statements
			reduce(2), // while, reduce: Statements
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // empty
			nil,      // lbrace
			nil,      // rbrace
			nil,      // @
			shift(8), // identifier
			nil,      // assign
			nil,      // terminator
			nil,      // [
			nil,      // intLit
			nil,      // ]
			nil,      // if
			nil,      // while
			nil,      // else
			nil,      // plus
			nil,      // minus
			nil,      // mul
			nil,      // ==
			nil,      // <
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			shift(9),  // assign
			nil,       // terminator
			shift(10), // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(11), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(13), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(11), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(13), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			shift(16), // assign
			nil,       // terminator
			shift(17), // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(18), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(20), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(22), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(24), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(16), // lbrace, reduce: Term
			nil,        // rbrace
			nil,        // @
			nil,        // identifier
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			reduce(16), // plus, reduce: Term
			reduce(16), // minus, reduce: Term
			reduce(16), // mul, reduce: Term
			reduce(16), // ==, reduce: Term
			reduce(16), // <, reduce: Term
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(27), // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			shift(29), // plus
			shift(30), // minus
			shift(31), // mul
			shift(32), // ==
			shift(33), // <
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(15), // lbrace, reduce: Term
			nil,        // rbrace
			nil,        // @
			nil,        // identifier
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			reduce(15), // plus, reduce: Term
			reduce(15), // minus, reduce: Term
			reduce(15), // mul, reduce: Term
			reduce(15), // ==, reduce: Term
			reduce(15), // <, reduce: Term
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(14), // lbrace, reduce: Expression
			nil,        // rbrace
			nil,        // @
			nil,        // identifier
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			reduce(14), // plus, reduce: Expression
			reduce(14), // minus, reduce: Expression
			reduce(14), // mul, reduce: Expression
			reduce(14), // ==, reduce: Expression
			reduce(14), // <, reduce: Expression
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(35), // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			shift(29), // plus
			shift(30), // minus
			shift(31), // mul
			shift(32), // ==
			shift(33), // <
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(18), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(20), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(37), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			nil,        // identifier
			nil,        // assign
			reduce(16), // terminator, reduce: Term
			nil,        // [
			nil,        // intLit
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			reduce(16), // plus, reduce: Term
			reduce(16), // minus, reduce: Term
			reduce(16), // mul, reduce: Term
			reduce(16), // ==, reduce: Term
			reduce(16), // <, reduce: Term
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			shift(38), // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			shift(29), // plus
			shift(30), // minus
			shift(31), // mul
			shift(32), // ==
			shift(33), // <
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			nil,        // identifier
			nil,        // assign
			reduce(15), // terminator, reduce: Term
			nil,        // [
			nil,        // intLit
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			reduce(15), // plus, reduce: Term
			reduce(15), // minus, reduce: Term
			reduce(15), // mul, reduce: Term
			reduce(15), // ==, reduce: Term
			reduce(15), // <, reduce: Term
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			nil,        // identifier
			nil,        // assign
			reduce(14), // terminator, reduce: Expression
			nil,        // [
			nil,        // intLit
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			reduce(14), // plus, reduce: Expression
			reduce(14), // minus, reduce: Expression
			reduce(14), // mul, reduce: Expression
			reduce(14), // ==, reduce: Expression
			reduce(14), // <, reduce: Expression
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			nil,        // identifier
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			reduce(16), // ], reduce: Term
			nil,        // if
			nil,        // while
			nil,        // else
			reduce(16), // plus, reduce: Term
			reduce(16), // minus, reduce: Term
			reduce(16), // mul, reduce: Term
			reduce(16), // ==, reduce: Term
			reduce(16), // <, reduce: Term
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			shift(40), // ]
			nil,       // if
			nil,       // while
			nil,       // else
			shift(29), // plus
			shift(30), // minus
			shift(31), // mul
			shift(32), // ==
			shift(33), // <
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			nil,        // identifier
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			reduce(15), // ], reduce: Term
			nil,        // if
			nil,        // while
			nil,        // else
			reduce(15), // plus, reduce: Term
			reduce(15), // minus, reduce: Term
			reduce(15), // mul, reduce: Term
			reduce(15), // ==, reduce: Term
			reduce(15), // <, reduce: Term
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			nil,        // identifier
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			reduce(14), // ], reduce: Expression
			nil,        // if
			nil,        // while
			nil,        // else
			reduce(14), // plus, reduce: Expression
			reduce(14), // minus, reduce: Expression
			reduce(14), // mul, reduce: Expression
			reduce(14), // ==, reduce: Expression
			reduce(14), // <, reduce: Expression
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(12), // $, reduce: ElseBlock
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			reduce(12), // @, reduce: ElseBlock
			reduce(12), // identifier, reduce: ElseBlock
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			nil,        // ]
			reduce(12), // if, reduce: ElseBlock
			reduce(12), // while, reduce: ElseBlock
			shift(43),  // else
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // ==
			nil,        // <
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			reduce(3), // rbrace, reduce: Statements
			reduce(3), // @, reduce: Statements
			reduce(3), // identifier, reduce: Statements
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(3), // if, reduce: Statements
			reduce(3), // while, reduce: Statements
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(11), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(13), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			reduce(17), // identifier, reduce: Operation
			nil,        // assign
			nil,        // terminator
			nil,        // [
			reduce(17), // intLit, reduce: Operation
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // ==
			nil,        // <
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			reduce(18), // identifier, reduce: Operation
			nil,        // assign
			nil,        // terminator
			nil,        // [
			reduce(18), // intLit, reduce: Operation
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // ==
			nil,        // <
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			reduce(19), // identifier, reduce: Operation
			nil,        // assign
			nil,        // terminator
			nil,        // [
			reduce(19), // intLit, reduce: Operation
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // ==
			nil,        // <
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			reduce(20), // identifier, reduce: Operation
			nil,        // assign
			nil,        // terminator
			nil,        // [
			reduce(20), // intLit, reduce: Operation
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // ==
			nil,        // <
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			reduce(21), // identifier, reduce: Operation
			nil,        // assign
			nil,        // terminator
			nil,        // [
			reduce(21), // intLit, reduce: Operation
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // ==
			nil,        // <
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(8), // $, reduce: Statement
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			reduce(8), // @, reduce: Statement
			reduce(8), // identifier, reduce: Statement
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(8), // if, reduce: Statement
			reduce(8), // while, reduce: Statement
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			reduce(3), // rbrace, reduce: Statements
			reduce(3), // @, reduce: Statements
			reduce(3), // identifier, reduce: Statements
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(3), // if, reduce: Statements
			reduce(3), // while, reduce: Statements
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			shift(47), // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			shift(29), // plus
			shift(30), // minus
			shift(31), // mul
			shift(32), // ==
			shift(33), // <
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			shift(48), // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(9), // $, reduce: Statement
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			reduce(9), // @, reduce: Statement
			reduce(9), // identifier, reduce: Statement
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(9), // if, reduce: Statement
			reduce(9), // while, reduce: Statement
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(18), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(20), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			shift(50), // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(22), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(24), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(7), // $, reduce: Statement
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			reduce(7), // @, reduce: Statement
			reduce(7), // identifier, reduce: Statement
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(7), // if, reduce: Statement
			reduce(7), // while, reduce: Statement
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(35), // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			shift(54), // rbrace
			shift(55), // @
			shift(56), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			shift(57), // if
			shift(58), // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(13), // lbrace, reduce: Expression
			nil,        // rbrace
			nil,        // @
			nil,        // identifier
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			reduce(13), // plus, reduce: Expression
			reduce(13), // minus, reduce: Expression
			reduce(13), // mul, reduce: Expression
			reduce(13), // ==, reduce: Expression
			reduce(13), // <, reduce: Expression
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			shift(59), // rbrace
			shift(55), // @
			shift(56), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			shift(57), // if
			shift(58), // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // $, reduce: Statement
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			reduce(5), // @, reduce: Statement
			reduce(5), // identifier, reduce: Statement
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(5), // if, reduce: Statement
			reduce(5), // while, reduce: Statement
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			shift(60), // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			nil,        // identifier
			nil,        // assign
			reduce(13), // terminator, reduce: Expression
			nil,        // [
			nil,        // intLit
			nil,        // ]
			nil,        // if
			nil,        // while
			nil,        // else
			reduce(13), // plus, reduce: Expression
			reduce(13), // minus, reduce: Expression
			reduce(13), // mul, reduce: Expression
			reduce(13), // ==, reduce: Expression
			reduce(13), // <, reduce: Expression
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(18), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(20), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			nil,        // @
			nil,        // identifier
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			reduce(13), // ], reduce: Expression
			nil,        // if
			nil,        // while
			nil,        // else
			reduce(13), // plus, reduce: Expression
			reduce(13), // minus, reduce: Expression
			reduce(13), // mul, reduce: Expression
			reduce(13), // ==, reduce: Expression
			reduce(13), // <, reduce: Expression
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(11), // $, reduce: ElseBlock
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			reduce(11), // @, reduce: ElseBlock
			reduce(11), // identifier, reduce: ElseBlock
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			nil,        // ]
			reduce(11), // if, reduce: ElseBlock
			reduce(11), // while, reduce: ElseBlock
			nil,        // else
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // ==
			nil,        // <
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			reduce(2), // rbrace, reduce: Statements
			reduce(2), // @, reduce: Statements
			reduce(2), // identifier, reduce: Statements
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(2), // if, reduce: Statements
			reduce(2), // while, reduce: Statements
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // $, reduce: StatementBlock
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			reduce(4), // @, reduce: StatementBlock
			reduce(4), // identifier, reduce: StatementBlock
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(4), // if, reduce: StatementBlock
			reduce(4), // while, reduce: StatementBlock
			reduce(4), // else, reduce: StatementBlock
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(62), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			shift(63), // assign
			nil,       // terminator
			shift(64), // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(11), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(13), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(11), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(13), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // $, reduce: StatementBlock
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			reduce(4), // @, reduce: StatementBlock
			reduce(4), // identifier, reduce: StatementBlock
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(4), // if, reduce: StatementBlock
			reduce(4), // while, reduce: StatementBlock
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(67), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			shift(68), // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			shift(29), // plus
			shift(30), // minus
			shift(31), // mul
			shift(32), // ==
			shift(33), // <
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			shift(69), // assign
			nil,       // terminator
			shift(70), // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(18), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(20), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(22), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(24), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(74), // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			shift(29), // plus
			shift(30), // minus
			shift(31), // mul
			shift(32), // ==
			shift(33), // <
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(76), // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			shift(29), // plus
			shift(30), // minus
			shift(31), // mul
			shift(32), // ==
			shift(33), // <
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			shift(77), // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(10), // $, reduce: Statement
			nil,        // empty
			nil,        // lbrace
			nil,        // rbrace
			reduce(10), // @, reduce: Statement
			reduce(10), // identifier, reduce: Statement
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			nil,        // ]
			reduce(10), // if, reduce: Statement
			reduce(10), // while, reduce: Statement
			nil,        // else
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // ==
			nil,        // <
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(18), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(20), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(79), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			shift(80), // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			shift(29), // plus
			shift(30), // minus
			shift(31), // mul
			shift(32), // ==
			shift(33), // <
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			shift(81), // ]
			nil,       // if
			nil,       // while
			nil,       // else
			shift(29), // plus
			shift(30), // minus
			shift(31), // mul
			shift(32), // ==
			shift(33), // <
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			reduce(12), // rbrace, reduce: ElseBlock
			reduce(12), // @, reduce: ElseBlock
			reduce(12), // identifier, reduce: ElseBlock
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			nil,        // ]
			reduce(12), // if, reduce: ElseBlock
			reduce(12), // while, reduce: ElseBlock
			shift(83),  // else
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // ==
			nil,        // <
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			reduce(3), // rbrace, reduce: Statements
			reduce(3), // @, reduce: Statements
			reduce(3), // identifier, reduce: Statements
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(3), // if, reduce: Statements
			reduce(3), // while, reduce: Statements
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			reduce(8), // rbrace, reduce: Statement
			reduce(8), // @, reduce: Statement
			reduce(8), // identifier, reduce: Statement
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(8), // if, reduce: Statement
			reduce(8), // while, reduce: Statement
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			reduce(3), // rbrace, reduce: Statements
			reduce(3), // @, reduce: Statements
			reduce(3), // identifier, reduce: Statements
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(3), // if, reduce: Statements
			reduce(3), // while, reduce: Statements
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // $, reduce: Statement
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			reduce(6), // @, reduce: Statement
			reduce(6), // identifier, reduce: Statement
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(6), // if, reduce: Statement
			reduce(6), // while, reduce: Statement
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			shift(86), // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			shift(29), // plus
			shift(30), // minus
			shift(31), // mul
			shift(32), // ==
			shift(33), // <
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			shift(87), // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			reduce(9), // rbrace, reduce: Statement
			reduce(9), // @, reduce: Statement
			reduce(9), // identifier, reduce: Statement
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(9), // if, reduce: Statement
			reduce(9), // while, reduce: Statement
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			shift(88), // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			reduce(7), // rbrace, reduce: Statement
			reduce(7), // @, reduce: Statement
			reduce(7), // identifier, reduce: Statement
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(7), // if, reduce: Statement
			reduce(7), // while, reduce: Statement
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(76), // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			shift(90), // rbrace
			shift(55), // @
			shift(56), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			shift(57), // if
			shift(58), // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			shift(91), // rbrace
			shift(55), // @
			shift(56), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			shift(57), // if
			shift(58), // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			reduce(5), // rbrace, reduce: Statement
			reduce(5), // @, reduce: Statement
			reduce(5), // identifier, reduce: Statement
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(5), // if, reduce: Statement
			reduce(5), // while, reduce: Statement
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			shift(92), // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			shift(18), // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(20), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			reduce(11), // rbrace, reduce: ElseBlock
			reduce(11), // @, reduce: ElseBlock
			reduce(11), // identifier, reduce: ElseBlock
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			nil,        // ]
			reduce(11), // if, reduce: ElseBlock
			reduce(11), // while, reduce: ElseBlock
			nil,        // else
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // ==
			nil,        // <
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			reduce(4), // rbrace, reduce: StatementBlock
			reduce(4), // @, reduce: StatementBlock
			reduce(4), // identifier, reduce: StatementBlock
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(4), // if, reduce: StatementBlock
			reduce(4), // while, reduce: StatementBlock
			reduce(4), // else, reduce: StatementBlock
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			reduce(4), // rbrace, reduce: StatementBlock
			reduce(4), // @, reduce: StatementBlock
			reduce(4), // identifier, reduce: StatementBlock
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(4), // if, reduce: StatementBlock
			reduce(4), // while, reduce: StatementBlock
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			nil,       // terminator
			nil,       // [
			shift(94), // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			shift(95), // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			shift(29), // plus
			shift(30), // minus
			shift(31), // mul
			shift(32), // ==
			shift(33), // <
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			nil,       // rbrace
			nil,       // @
			nil,       // identifier
			nil,       // assign
			shift(96), // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			nil,       // if
			nil,       // while
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // lbrace
			reduce(10), // rbrace, reduce: Statement
			reduce(10), // @, reduce: Statement
			reduce(10), // identifier, reduce: Statement
			nil,        // assign
			nil,        // terminator
			nil,        // [
			nil,        // intLit
			nil,        // ]
			reduce(10), // if, reduce: Statement
			reduce(10), // while, reduce: Statement
			nil,        // else
			nil,        // plus
			nil,        // minus
			nil,        // mul
			nil,        // ==
			nil,        // <
		},
	},
	actionRow{ // S96
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // lbrace
			reduce(6), // rbrace, reduce: Statement
			reduce(6), // @, reduce: Statement
			reduce(6), // identifier, reduce: Statement
			nil,       // assign
			nil,       // terminator
			nil,       // [
			nil,       // intLit
			nil,       // ]
			reduce(6), // if, reduce: Statement
			reduce(6), // while, reduce: Statement
			nil,       // else
			nil,       // plus
			nil,       // minus
			nil,       // mul
			nil,       // ==
			nil,       // <
		},
	},
}
