// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 9

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Program
		2,  // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		3,  // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		13, // Expression
		15, // Term
		-1, // Operation
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		16, // Expression
		15, // Term
		-1, // Operation
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		21, // Expression
		23, // Term
		-1, // Operation
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		25, // Expression
		27, // Term
		-1, // Operation
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Program
		-1, // Statements
		28, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		30, // Operation
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Program
		-1, // Statements
		36, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		30, // Operation
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		39, // Expression
		23, // Term
		-1, // Operation
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		42, // Operation
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		44, // Operation
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		45, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Program
		47, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		48, // Term
		-1, // Operation
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Program
		49, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		42, // Operation
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		53, // Term
		-1, // Operation
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		55, // Term
		-1, // Operation
	},
	gotoRow{ // S45
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S46
		-1, // S'
		-1, // Program
		-1, // Statements
		56, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S47
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		57, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S48
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S49
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		57, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S50
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S51
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S52
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S53
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S54
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		67, // Expression
		23, // Term
		-1, // Operation
	},
	gotoRow{ // S55
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S56
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S57
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S58
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S59
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S60
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S61
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		71, // Expression
		15, // Term
		-1, // Operation
	},
	gotoRow{ // S62
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		72, // Expression
		15, // Term
		-1, // Operation
	},
	gotoRow{ // S63
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S64
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S65
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S66
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S67
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		42, // Operation
	},
	gotoRow{ // S68
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S69
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		78, // Expression
		23, // Term
		-1, // Operation
	},
	gotoRow{ // S70
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		79, // Expression
		27, // Term
		-1, // Operation
	},
	gotoRow{ // S71
		-1, // S'
		-1, // Program
		-1, // Statements
		80, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		30, // Operation
	},
	gotoRow{ // S72
		-1, // S'
		-1, // Program
		-1, // Statements
		82, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		30, // Operation
	},
	gotoRow{ // S73
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S74
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S75
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S76
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		86, // Expression
		23, // Term
		-1, // Operation
	},
	gotoRow{ // S77
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S78
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		42, // Operation
	},
	gotoRow{ // S79
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		44, // Operation
	},
	gotoRow{ // S80
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		90, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S81
		-1, // S'
		-1, // Program
		92, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S82
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S83
		-1, // S'
		-1, // Program
		93, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S84
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S85
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S86
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		42, // Operation
	},
	gotoRow{ // S87
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S88
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S89
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S90
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S91
		-1, // S'
		-1, // Program
		-1, // Statements
		98, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S92
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		57, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S93
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		57, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S94
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S95
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S96
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S97
		-1,  // S'
		-1,  // Program
		-1,  // Statements
		-1,  // StatementBlock
		-1,  // Statement
		-1,  // ElseBlock
		103, // Expression
		23,  // Term
		-1,  // Operation
	},
	gotoRow{ // S98
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S99
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S100
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S101
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S102
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S103
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		42, // Operation
	},
	gotoRow{ // S104
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S105
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S106
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // StatementBlock
		-1, // Statement
		-1, // ElseBlock
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
}
