// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 7

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Program
		2,  // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Program
		-1, // Statements
		3,  // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		10, // Expression
		11, // Term
		-1, // Operation
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		13, // Expression
		11, // Term
		-1, // Operation
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		15, // Operation
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		15, // Operation
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		19, // Term
		-1, // Operation
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Program
		-1, // Statements
		-1, // Statement
		-1, // Expression
		-1, // Term
		-1, // Operation
	},
}
