// Code generated by gocc; DO NOT EDIT.

package parser

import (
	"minicompiler/ast" 
)

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib, interface{}) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Program	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Program : Statements	<< ast.NewProgram(X[0]) >>`,
		Id:         "Program",
		NTType:     1,
		Index:      1,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewProgram(X[0])
		},
	},
	ProdTabEntry{
		String: `Statements : Statements Statement	<< ast.AppendStatement(X[0], X[1]) >>`,
		Id:         "Statements",
		NTType:     2,
		Index:      2,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendStatement(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `Statements : empty	<< ast.NewStatementList() >>`,
		Id:         "Statements",
		NTType:     2,
		Index:      3,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewStatementList()
		},
	},
	ProdTabEntry{
		String: `Statement : "@" identifier assign Expression terminator	<< ast.NewIdentInit(X[1], X[3]) >>`,
		Id:         "Statement",
		NTType:     3,
		Index:      4,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIdentInit(X[1], X[3])
		},
	},
	ProdTabEntry{
		String: `Statement : identifier assign Expression terminator	<< ast.NewAssignStatement(X[0], X[2]) >>`,
		Id:         "Statement",
		NTType:     3,
		Index:      5,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewAssignStatement(X[0], X[2])
		},
	},
	ProdTabEntry{
		String: `Expression : Expression Operation Term	<< ast.NewInfixExpression(X[0], X[2], X[1]) >>`,
		Id:         "Expression",
		NTType:     4,
		Index:      6,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewInfixExpression(X[0], X[2], X[1])
		},
	},
	ProdTabEntry{
		String: `Expression : Term	<<  >>`,
		Id:         "Expression",
		NTType:     4,
		Index:      7,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term : intLit	<< ast.NewIntegerLiteral(X[0]) >>`,
		Id:         "Term",
		NTType:     5,
		Index:      8,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIntegerLiteral(X[0])
		},
	},
	ProdTabEntry{
		String: `Term : identifier	<< ast.NewIdentExpression(X[0]) >>`,
		Id:         "Term",
		NTType:     5,
		Index:      9,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIdentExpression(X[0])
		},
	},
	ProdTabEntry{
		String: `Operation : plus	<<  >>`,
		Id:         "Operation",
		NTType:     6,
		Index:      10,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operation : minus	<<  >>`,
		Id:         "Operation",
		NTType:     6,
		Index:      11,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
}
